name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, macos-11, ubuntu-22.04]
        addrsize: ["64"]
        include:
          - os: windows-2022
            addrsize: "32"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: secondlife/action-autobuild@release/v3
        with:
          addrsize: ${{ matrix.addrsize }}
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: secondlife/action-autobuild-release@v1
        with:
          public: true
